int stringtodouble (const char *str, double *v);
int stringtoint (const char *str, int *v);
double getdouble (const char *display);
int getint (const char *display);
char *getstring (const char *display);
double getfrequency(void);
double getcapacitance(void);
double getinductance(void);
double getresistance(void);
double getpower(void);
double getdistance(void);
void showfrequency(double);
void showcapacitance(double);
void showinductance(double);
void showpower(double);
void showdistance(double);
void showresistance(double);
double complex getimpedance(void);
