int stringtodouble (const char *str, double *v);
int stringtoint (const char *str, int *v);
double getdouble (const char *display);
int getint (const char *display);
char *getstring (const char *display);
double getfrequency(const char *display);
double getcapacitance(const char *display);
double getinductance(const char *display);
double getresistance(const char *display);
double getpower(const char *display);
double getdistance(const char *display);
double getvoltage(const char *display);
double getamperage(const char *display);
void showfrequency(double);
void showcapacitance(double);
void showinductance(double);
void showpower(double);
void showdistance(double);
void showresistance(double);
void showvoltage(double);
void showamperage(double);
double complex getimpedance(const char *display);
